<?php

namespace Database\Seeders;

use App\Models\EconomicSector;
use Illuminate\Database\Seeder;

class EconomicSectorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sectors = [
            ['code' => '011110', 'name' => 'Pertanian Padi'],
            ['code' => '011121', 'name' => 'Pertanian Palawija Jagung'],
            ['code' => '011122', 'name' => 'Pertanian Palawija Ketela pohon'],
            ['code' => '011123', 'name' => 'Pertanian Palawija Ubi jalar'],
            ['code' => '011124', 'name' => 'Pertanian Palawija Umbi-umbian lainnya'],
            ['code' => '011125', 'name' => 'Pertanian Palawija Kacang tanah'],
            ['code' => '011126', 'name' => 'Pertanian Palawija Kedele'],
            ['code' => '011129', 'name' => 'Pertanian Palawija Kacang-kacangan lainnya'],
            ['code' => '011130', 'name' => 'Perkebunan Tebu dan Tanaman Pemanis Lainnya'],
            ['code' => '011140', 'name' => 'Perkebunan Tembakau'],
            ['code' => '011150', 'name' => 'Perkebunan Karet dan Penghasil Getah Lainnya'],
            ['code' => '011160', 'name' => 'Perkebunan Tanaman Bahan Baku Tekstil dan Sejenisnya'],
            ['code' => '011170', 'name' => 'Perkebunan Tanaman Obat / Bahan Farmasi'],
            ['code' => '011180', 'name' => 'Perkebunan Tanaman Minyak Atsiri'],
            ['code' => '011190', 'name' => 'Perkebunan Tanaman Lainnya yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '011211', 'name' => 'Pertanian Hortikultura Sayuran yang dipanen Sekali Bawang Merah'],
            ['code' => '011219', 'name' => 'Pertanian Hortikultura Sayuran yang dipanen Sekali Lainnya'],
            ['code' => '011220', 'name' => 'Pertanian Hortikultura Sayuran yang dipanen Lebih dari Sekali'],
            ['code' => '011231', 'name' => 'Pertanian Hortikultura Bunga-bungaan Anggrek'],
            ['code' => '011239', 'name' => 'Pertanian Hortikultura Bunga-bungaan Lainnya'],
            ['code' => '011240', 'name' => 'Pertanian Tanaman Hias Lainnya'],
            ['code' => '011250', 'name' => 'Pembibitan dan Pembenihan Hortikultura Sayuran dan Bunga-bungaan'],
            ['code' => '011311', 'name' => 'Pertanian Buah-buahan Musiman Jeruk'],
            ['code' => '011319', 'name' => 'Pertanian Buah-buahan Musiman Lainnya'],
            ['code' => '011321', 'name' => 'Pertanian Buah-buahan Sepanjang Tahun Pisang'],
            ['code' => '011329', 'name' => 'Pertanian Buah-buahan Sepanjang Tahun Lainnya'],
            ['code' => '011330', 'name' => 'Perkebunan Kelapa'],
            ['code' => '011340', 'name' => 'Perkebunan Kelapa Sawit'],
            ['code' => '011351', 'name' => 'Perkebunan Tanaman Kopi'],
            ['code' => '011352', 'name' => 'Perkebunan Tanaman Teh'],
            ['code' => '011353', 'name' => 'Perkebunan Tanaman Coklat (Kakao)'],
            ['code' => '011360', 'name' => 'Perkebunan Jambu Mete'],
            ['code' => '011370', 'name' => 'Perkebunan Lada'],
            ['code' => '011380', 'name' => 'Perkebunan Cengkeh'],
            ['code' => '011391', 'name' => 'Perkebunan Tanaman Rempah Panili'],
            ['code' => '011392', 'name' => 'Perkebunan Tanaman Rempah Pala'],
            ['code' => '011399', 'name' => 'Perkebunan Tanaman Rempah yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '012110', 'name' => 'Pembibitan dan Budidaya Sapi Potong'],
            ['code' => '012191', 'name' => 'Pembibitan dan Budidaya Domba dan Kambing Potong'],
            ['code' => '012192', 'name' => 'Pembibitan dan Budidaya Ternak Perah'],
            ['code' => '012210', 'name' => 'Pembibitan dan Budidaya Babi'],
            ['code' => '012291', 'name' => 'Pembibitan dan Budidaya Unggas'],
            ['code' => '013000', 'name' => 'Kombinasi Pertanian Atau Perkebunan Dengan Peternakan (Mixed Farming)'],
            ['code' => '014000', 'name' => 'Jasa Pertanian, Perkebunan dan Peternakan'],
            ['code' => '015000', 'name' => 'Perburuan Penangkapan dan Penangkaran Satwa Liar'],
            ['code' => '020100', 'name' => 'Pengusahaan Hutan Tanaman'],
            ['code' => '020200', 'name' => 'Pengusahaan Hutan Alam'],
            ['code' => '020300', 'name' => 'Pengusahaan Hasil Hutan Selain Kayu'],
            ['code' => '020400', 'name' => 'Jasa Kehutanan'],
            ['code' => '020500', 'name' => 'Usaha Kehutanan Lainnya'],
            ['code' => '050111', 'name' => 'Penangkapan Ikan Tuna'],
            ['code' => '050119', 'name' => 'Penangkapan Ikan Lainnya'],
            ['code' => '050121', 'name' => 'Penangkapan Udang Laut'],
            ['code' => '050122', 'name' => 'Penangkapan Crustacea Lainnya di Laut'],
            ['code' => '050190', 'name' => 'Perikanan Lainnya'],
            ['code' => '052000', 'name' => 'Budidaya Biota di Laut'],
            ['code' => '050211', 'name' => 'Budidaya Biota Laut Udang'],
            ['code' => '050212', 'name' => 'Budidaya Biota Laut Tuna'],
            ['code' => '050213', 'name' => 'Budidaya Biota Laut Rumput Laut'],
            ['code' => '050219', 'name' => 'Budidaya Biota Laut Lainnya'],
            ['code' => '050220', 'name' => 'Pembenihan Biota Laut'],
            ['code' => '053000', 'name' => 'Penangkapan Biota di Perairan Umum'],
            ['code' => '050310', 'name' => 'Penangkapan Ikan di Perairan Umum'],
            ['code' => '050320', 'name' => 'Penangkapan Crustacea, Mollusca, dan Biota Lainnya di Perairan Umum'],
            ['code' => '054000', 'name' => 'Budidaya Biota Air Tawar dan Air Payau'],
            ['code' => '050411', 'name' => 'Budidaya Biota Air Tawar Udang'],
            ['code' => '050419', 'name' => 'Budidaya Biota Air Tawar Lainnya'],
            ['code' => '050421', 'name' => 'Budidaya Biota Air Payau Udang'],
            ['code' => '050429', 'name' => 'Budidaya Biota Air Payau Lainnya'],
            ['code' => '050490', 'name' => 'Pembenihan Biota Air Tawar dan Air Payau'],
            ['code' => '055000', 'name' => 'Jasa Perikanan'],
            ['code' => '050510', 'name' => 'Jasa Sarana Produksi Perikanan Laut'],
            ['code' => '050580', 'name' => 'Jasa Sarana Produksi Perikanan Darat'],
            ['code' => '050590', 'name' => 'Jasa Perikanan Lainnya'],
            ['code' => '101000', 'name' => 'Pertambangan Batubara, Penggalian Gambut, dan Gasifikasi Batubara'],
            ['code' => '102000', 'name' => 'Pembuatan Briket Batubara'],
            ['code' => '111010', 'name' => 'Pertambangan Minyak dan Gas Bumi'],
            ['code' => '111020', 'name' => 'Pengusahaan Tenaga Panas Bumi'],
            ['code' => '112000', 'name' => 'Jasa Pertambangan Minyak dan Gas Bumi'],
            ['code' => '120000', 'name' => 'Pertambangan Bijih Uranium dan Thorium'],
            ['code' => '131000', 'name' => 'Pertambangan Pasir Besi dan Bijih Besi'],
            ['code' => '132000', 'name' => 'Pertambangan Logam dan Bijih Timah'],
            ['code' => '132010', 'name' => 'Pertambangan Bijih Timah'],
            ['code' => '132020', 'name' => 'Pertambangan Bijih Bauksit'],
            ['code' => '132030', 'name' => 'Pertambangan Bijih Tembaga'],
            ['code' => '132040', 'name' => 'Pertambangan Bijih Nikel'],
            ['code' => '132061', 'name' => 'Pertambangan Emas'],
            ['code' => '132062', 'name' => 'Pertambangan Perak'],
            ['code' => '132090', 'name' => 'Bahan Galian Lainnya yang Tidak Mengandung Bijih Besi'],
            ['code' => '141000', 'name' => 'Penggalian Batu-batuan, Tanah Liat dan Pasir'],
            ['code' => '142000', 'name' => 'Pertambangan dan Penggalian yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '142100', 'name' => 'Pertambangan Mineral, Bahan Kimia dan Bahan Pupuk'],
            ['code' => '142200', 'name' => 'Ekstraksi Garam'],
            ['code' => '142900', 'name' => 'Pertambangan dan Penggalian Lainnya'],
            ['code' => '151000', 'name' => 'Pengolahan dan Pengawetan Daging, Ikan, Buah-buahan, Sayuran, Minyak dan Lemak'],
            ['code' => '151110', 'name' => 'Industri Pemotongan Hewan'],
            ['code' => '151120', 'name' => 'Industri Pengolahan dan Pengawetan Daging'],
            ['code' => '151200', 'name' => 'Industri Pengolahan dan Pengawetan Ikan dan Biota Perairan Lainnya'],
            ['code' => '151300', 'name' => 'Industri Pengolahan, Pengawetan Buah-buahan dan Sayuran'],
            ['code' => '151410', 'name' => 'Industri Minyak Mentah (Minyak Makan) dari Nabati dan Hewani'],
            ['code' => '151430', 'name' => 'lndustri Minyak Goreng dari Kelapa'],
            ['code' => '151440', 'name' => 'Industri Minyak Goreng dari Kelapa Sawit Mentah'],
            ['code' => '151450', 'name' => 'Industri Minyak Goreng dari Biji Kelapa Sawit'],
            ['code' => '152000', 'name' => 'Industri Susu dan Makanan dari Susu'],
            ['code' => '153000', 'name' => 'Industri Penggilingan Padi-padian, Tepung, dan Pakan Ternak'],
            ['code' => '153110', 'name' => 'Industri Penggilingan Padi dan Penyosohan Beras'],
            ['code' => '153180', 'name' => 'lndustri Kopra'],
            ['code' => '153190', 'name' => 'Industri Penggilingan Lainnya'],
            ['code' => '153200', 'name' => 'Industri Tepung dan Pati'],
            ['code' => '153300', 'name' => 'Industri Pakan Ternak'],
            ['code' => '154000', 'name' => 'Industri Makanan Lainnya'],
            ['code' => '154100', 'name' => 'Industri Roti dan Sejenisnya'],
            ['code' => '154200', 'name' => 'Industri Gula dan Pengolahan Gula'],
            ['code' => '154300', 'name' => 'Industri Coklat dan Kernbang Gula'],
            ['code' => '154400', 'name' => 'Industri Makaroni, Mie, Spagheti, Bihun, So\'un dan Sejenisnya'],
            ['code' => '154911', 'name' => 'Industri Pengolahan Teh'],
            ['code' => '154912', 'name' => 'Industri Pengolahan Kopi'],
            ['code' => '154930', 'name' => 'lndustri Kecap'],
            ['code' => '154940', 'name' => 'lndustri Tempe dan Tahu'],
            ['code' => '154990', 'name' => 'lndustri Makanan yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '160000', 'name' => 'INDUSTRI PENGOLAHAN TEMBAKAU'],
            ['code' => '161000', 'name' => 'Industri Pengolahan Tembakau'],
            ['code' => '160010', 'name' => 'lndustri Pengeringan dan Pengolahan Tembakau'],
            ['code' => '160050', 'name' => 'Industri Rokok'],
            ['code' => '160090', 'name' => 'Industri Bumbu Rokok Serta Kelengkapan Rokok Lainnya'],
            ['code' => '172000', 'name' => 'Industri Barang Jadi Tekstil dan Permadani'],
            ['code' => '173000', 'name' => 'Industri Perajutan Industri Perajutan'],
            ['code' => '174000', 'name' => 'Industri Kapuk'],
            ['code' => '181000', 'name' => 'Industri Pakaian Jadi dan perlengkapannya, Kecuali Pakaian Jadi Berbulu'],
            ['code' => '182000', 'name' => 'Industri Pakaian Jadi Barang Jadi dari Kulit Berbulu dan Pencelupan Bulu'],
            ['code' => '191000', 'name' => 'Industri Kulit dan Barang dari Kulit (Termasuk Kulit Buatan)'],
            ['code' => '192000', 'name' => 'Industri Alas Kaki'],
            ['code' => '202100', 'name' => 'Industri Kayu Lapis, Veneer, dan Sejenisnya'],
            ['code' => '202900', 'name' => 'Industri Anyam-anyaman, Kerajinan, Ukiran dari Kayu, dan Industri Barang Lain dari Kayu'],
            ['code' => '211000', 'name' => 'Industri Kertas, Barang dari Kertas dan Sejenisnya'],
            ['code' => '210100', 'name' => 'Industri Bubur Kertas (Pulp), Kertas dan Karton / Paper Board'],
            ['code' => '210200', 'name' => 'Industri Kemasan dan Kotak dari Kertas dan Karton'],
            ['code' => '210900', 'name' => 'Industri Barang dari Kertas dan Kartan yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '221000', 'name' => 'Industri Penerbitan'],
            ['code' => '222000', 'name' => 'Industri Percetakan dan Kegiatan yang Berkaitan Dengan Pencetakan Termasuk Reproduksi / Cetak Ulang)'],
            ['code' => '223000', 'name' => 'Reproduksi Media Rekaman, Film, dan Video'],
            ['code' => '231000', 'name' => 'Industri Barang-barang dari Batubara'],
            ['code' => '232000', 'name' => 'Industri Pengilangan Minyak Bumi, Pengolahan Gas Bumi, dan Industri Barang-barang dari Hasil Pengilangan Minyak Bumi'],
            ['code' => '233000', 'name' => 'Pengolahan Bahan Bakar Nuklir (Nuclear Fuel)'],
            ['code' => '241000', 'name' => 'Industri Bahan Kimia Industri'],
            ['code' => '241100', 'name' => 'Industri Kimia Dasar, Kecuali Pupuk'],
            ['code' => '241200', 'name' => 'Industri Pupuk'],
            ['code' => '241300', 'name' => 'Industri Plastik dan Karet Buatan'],
            ['code' => '242000', 'name' => 'Industri Barang-barang Kimia lainnya'],
            ['code' => '242100', 'name' => 'Industri Bahan Baku Pemberantas Hama dan Pemberantas Hama Termasuk Zat Pengatur Tumbuh'],
            ['code' => '242200', 'name' => 'Industri Cat, Pernis dan Lak'],
            ['code' => '242300', 'name' => 'Industri Farmasi dan Jamu'],
            ['code' => '242400', 'name' => 'Industri Sabun dan Bahan Pembersih Keperluan Rumah Tangga, Kosmetik dan Sejenisnya'],
            ['code' => '242940', 'name' => 'Industri Minyak Atsiri'],
            ['code' => '242990', 'name' => 'Industri Bahan Kimia dan Barang Kimia Lainnya'],
            ['code' => '243000', 'name' => 'Industri Serat Buatan'],
            ['code' => '251000', 'name' => 'Industri Karet dan Barang dari Karet'],
            ['code' => '251210', 'name' => 'Industri Pengasapan Karet'],
            ['code' => '251220', 'name' => 'Industri Remilling Karet'],
            ['code' => '251230', 'name' => 'Industri Karet Remah (Crumb Rubber)'],
            ['code' => '251900', 'name' => 'Industri Barang-barang lain dari Karet'],
            ['code' => '252000', 'name' => 'Industri Barang dari Plastik'],
            ['code' => '261000', 'name' => 'Industri Gelas dan Barang dari Gelas'],
            ['code' => '262000', 'name' => 'Industri Barang-barang dari Porselin'],
            ['code' => '263000', 'name' => 'Industri Pengolahan Tanah Liat / Keramik'],
            ['code' => '264000', 'name' => 'Industri Semen, Kapur dan Gips, Serta Barang-barang dari Semen, dan Kapur'],
            ['code' => '265000', 'name' => 'Industri Barang-barang dari Batu'],
            ['code' => '266000', 'name' => 'Industri Barang-barang dari Asbes'],
            ['code' => '269000', 'name' => 'Industri Barang-barang Galian Bukan Logam Lainnya'],
            ['code' => '271000', 'name' => 'Industri Logam Dasar Besi dan Baja'],
            ['code' => '272000', 'name' => 'Industri Logam Dasar Bukan Besi'],
            ['code' => '273000', 'name' => 'Industri Pengecoran logam'],
            ['code' => '273100', 'name' => 'Industri Pengecoran Besi dan Baja'],
            ['code' => '273200', 'name' => 'Industri pengecoran Logam Bukan Besi dan Baja'],
            ['code' => '281000', 'name' => 'Industri Barang-barang Logam Siap Pasang Untuk Bangunan, Pembuatan Tangki, dan Generator Uap'],
            ['code' => '289000', 'name' => 'Industri Barang Logam Lainnya, dan Kegiatan Jasa Pembuatan Barang-barang dari Logam'],
            ['code' => '289300', 'name' => 'Industri Alat-alat Pertanian, Pertukangan, Pemotong, dan Peralatan lainnya dari Logam'],
            ['code' => '289900', 'name' => 'Industri Barang Logam yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '291000', 'name' => 'Industri Mesin-mesin Umum'],
            ['code' => '292000', 'name' => 'Industri Mesin-mesin Untuk Keperluan Khusus'],
            ['code' => '292100', 'name' => 'Industri Mesin Pertanian dan Kehutanan, Serta Jasa Penunjang Pemeliharaan dan Perbaikannya'],
            ['code' => '292400', 'name' => 'Industri Mesin-mesin Untuk Pertambangan, Penggalian dan Konstruksi'],
            ['code' => '292500', 'name' => 'lndustri Mesin Untuk Pengolahan Makanan, Minuman dan Tembakau'],
            ['code' => '292600', 'name' => 'Industri Mesin-mesin Tekstil, Produk Tekstil, dan Barang-barang dari Kulit'],
            ['code' => '292900', 'name' => 'Industri Mesin-mesin Khusus Lainnya'],
            ['code' => '293000', 'name' => 'Industri Peralatan Rumah Tangga yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '300000', 'name' => 'Industri Mesin dan Peralatan Kantor, Akuntansi, dan Pengolahan Data'],
            ['code' => '311000', 'name' => 'Industri Motor Listrik, Generator, dan Transformator'],
            ['code' => '312000', 'name' => 'Industri Peralatan Pengontrol dan Pendistribusian Listrik'],
            ['code' => '313000', 'name' => 'Industri Kabel Listrik dan Telepon'],
            ['code' => '314000', 'name' => 'Industri Akumulator Listrik dan Batu Baterai'],
            ['code' => '315000', 'name' => 'Industri Bola Lampu Pijar dan Lampu Penerangan'],
            ['code' => '319000', 'name' => 'Industri Peralatan Listrik yang Tidak Diklasifikasikan di Tempat lain'],
            ['code' => '321000', 'name' => 'Industri Tabung dan Katup Elektronik Serta Komponen Elektronik lainnya'],
            ['code' => '322000', 'name' => 'Industri Alat Transmisi Komunikasi'],
            ['code' => '323000', 'name' => 'Industri Radio, Televisi, Alat-alat Rekaman Suara dan Gambar, dan Sejenisnya'],
            ['code' => '331000', 'name' => 'Industri Peralatan Kedokteran, dan Peralatan Untuk Mengukur, Memeriksa, Menguji, dan Bagian Lainnya, Kecuali Alat-alat Optik'],
            ['code' => '332000', 'name' => 'Industri Instrumen Optik dan Peralatan Fotografi'],
            ['code' => '333000', 'name' => 'Industri Jam, Lonceng, dan Sejenisnya'],
            ['code' => '341000', 'name' => 'Industri Kendaraan Bermotor Roda Empat Atau Lebih'],
            ['code' => '342000', 'name' => 'Industri Karoseri Kendaraan Bermotor Roda Empat Atau Lebih'],
            ['code' => '343000', 'name' => 'Industri Perlengkapan dan Komponen Kendaraan Bermotor Roda Empat Atau Lebih'],
            ['code' => '351000', 'name' => 'Industri Pembuatan dan Perbaikan Kapal dan Perahu'],
            ['code' => '352000', 'name' => 'Industri Kereta Api, Bagian-bagian dan Perlengkapannya, Serta Perbaikan Kereta Api'],
            ['code' => '353000', 'name' => 'Industri Pesawat Terbang dan Perlengkapannya Serta Perbaikan Pesawat Terbang'],
            ['code' => '359000', 'name' => 'Industri Alat Angkut lainnya'],
            ['code' => '359100', 'name' => 'Industri Kendaraan Bermotor Roda Dua dan Tiga Serta Komponen dan Perlengkapannya'],
            ['code' => '359900', 'name' => 'Industri Alat Angkut yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '361000', 'name' => 'Industri Furnitur'],
            ['code' => '369000', 'name' => ' Industri Pengolahan Lainnya'],
            ['code' => '371000', 'name' => 'Daur Ulang Barang-barang Logam'],
            ['code' => '372000', 'name' => 'Daur Ulang Barang-barang Bukan logam'],
            ['code' => '401000', 'name' => 'Ketenagalistrikan'],
            ['code' => '401001', 'name' => 'Ketenagalistrikan Pedesaan'],
            ['code' => '401002', 'name' => 'Ketenagalistrikan Lainnya'],
            ['code' => '402000', 'name' => 'Gas'],
            ['code' => '403000', 'name' => 'Uap dan Air Panas'],
            ['code' => '410000', 'name' => 'Pengadaan dan Penyaluran Air Bersih'],
            ['code' => '451000', 'name' => 'Penyiapan lahan'],
            ['code' => '451001', 'name' => ' Penyiapan Tanah Pemukiman Transmigrasi (PTPT)'],
            ['code' => '451002', 'name' => 'Pencetakan Lahan Sawah'],
            ['code' => '451009', 'name' => 'Penyiapan Lahan Lainnya'],
            ['code' => '452000', 'name' => 'Konstruksi Gedung dan Bangunan Sipil'],
            ['code' => '452111', 'name' => 'Konstruksi Perumahan Sederhana - Bank Tabungan Negara'],
            ['code' => '452112', 'name' => ' Konstruksi Perumahan Sederhana - Perumnas'],
            ['code' => '452113', 'name' => 'Konstruksi Perumahan Sederhana - Lainnya Tipe s.d. 21'],
            ['code' => '452114', 'name' => 'Konstruksi Perumahan Sederhana - Lainnya Tipe 22 s.d. 70'],
            ['code' => '452115', 'name' => 'Konstruksi Perumahan Menengah, Besar, Mewah (Tipe Diatas 70)'],
            ['code' => '452120', 'name' => 'Konstruksi Gedung Perkantoran'],
            ['code' => '452130', 'name' => 'Konstruksi Gedung Industri'],
            ['code' => '452141', 'name' => 'Konstruksi Gedung Perbelanjaan Pasar Inpres'],
            ['code' => '452149', 'name' => 'Konstruksi Gedung Perbelanjaan Lainnya'],
            ['code' => '452190', 'name' => 'Konstruksi Gedung Lainnya'],
            ['code' => '452211', 'name' => 'Bangunan Jalan Raya'],
            ['code' => '452212', 'name' => 'Bangunan Jalan Tol'],
            ['code' => '452213', 'name' => 'Bangunan Jalan Jembatan dan Landasan'],
            ['code' => '452220', 'name' => 'Bangunan Jalan dan Jembatan Kereta Api'],
            ['code' => '452240', 'name' => 'Bangunan Pengairan (Irigasi)'],
            ['code' => '452270', 'name' => 'Bangunan Dermaga (Pelabuhan)'],
            ['code' => '452290', 'name' => 'Bangunan Sipil Lainnya'],
            ['code' => '452301', 'name' => 'Konstruksi Bangunan Listrik Pedesaan'],
            ['code' => '452309', 'name' => 'Konstruksi Bangunan Elektrikal dan Komunikasi Lainnya'],
            ['code' => '452400', 'name' => 'Konstruksi Khusus'],
            ['code' => '453000', 'name' => 'Instalasi Gedung dan Bangunan Sipil'],
            ['code' => '453100', 'name' => 'Instalasi Gedung'],
            ['code' => '453200', 'name' => 'Instalasi Bangunan Sipil'],
            ['code' => '454000', 'name' => 'Penyelesaian Konstruksi Gedung'],
            ['code' => '455000', 'name' => 'Penghancur Bangunan Dengan Operatornya'],
            ['code' => '501000', 'name' => 'Penjualan Mobil'],
            ['code' => '502000', 'name' => 'Penjualan Suku Cadang dan Aksesoris Mobil'],
            ['code' => '503000', 'name' => 'Penjualan Sepeda Motor Serta Suku Cadang dan Aksesorisnya'],
            ['code' => '503001', 'name' => ' Penjualan Sepeda Motor'],
            ['code' => '503002', 'name' => 'Penjualan Suku Cadang dan Aksesoris Sepeda Motor'],
            ['code' => '504000', 'name' => 'Perdagangan Eceran Bahan Bakar Kendaraan'],
            ['code' => '511000', 'name' => 'Perdagangan Besar Berdasarkan Balas Jasa (Fee) Atau Kontrak'],
            ['code' => '512000', 'name' => 'Perdagangan Besar Dalam Negeri Hasil Pertanian, Binatang Hidup, Makanan, Minuman, dan Tembakau'],
            ['code' => '512111', 'name' => 'Perdagangan Jagung'],
            ['code' => '512112', 'name' => 'Perdagangan Tembakau'],
            ['code' => '512113', 'name' => 'Perdagangan Karet'],
            ['code' => '512114', 'name' => 'Perdagangan Cengkeh'],
            ['code' => '512115', 'name' => 'Perdagangan Lada'],
            ['code' => '512116', 'name' => 'Perdagangan Kelapa dan Kelapa Sawit'],
            ['code' => '512117', 'name' => 'Perdagangan Kapas'],
            ['code' => '512119', 'name' => 'Perdagangan Besar Dalam Negeri Hasil Pertanian Lainnya'],
            ['code' => '512120', 'name' => 'Perdagangan Besar Dalam Negeri Binatang Hidup'],
            ['code' => '512130', 'name' => 'Perdagangan Besar Dalam Negeri Hasil Perikanan'],
            ['code' => '512141', 'name' => 'Perdagangan Kayu'],
            ['code' => '512149', 'name' => 'Perdagangan Besar Dalam Negeri Hasil Kehutanan dan Perburuan Lainnya'],
            ['code' => '512201', 'name' => 'Perdagangan Dalam Negeri Beras'],
            ['code' => '512202', 'name' => 'Perdagangan Dalam Negeri Gula'],
            ['code' => '512203', 'name' => 'Perdagangan Dalam Negeri Kopi'],
            ['code' => '512204', 'name' => 'Perdagangan Dalam Negeri Teh'],
            ['code' => '512205', 'name' => 'Perdagangan Dalam Negeri Garam'],
            ['code' => '512206', 'name' => 'Perdagangan Dalam Negeri Minyak Kelapa Sawit'],
            ['code' => '512207', 'name' => 'Perdagangan Dalam Negeri Kopra'],
            ['code' => '512208', 'name' => 'Perdagangan Dalam Negeri Rokok'],
            ['code' => '512209', 'name' => 'Perdagangan Dalam Negeri Makanan, Minuman dan Tembakau Lainnya'],
            ['code' => '513100', 'name' => 'Perdagangan Besar Tekstil, Pakaian Jadi, dan Kulit'],
            ['code' => '513900', 'name' => 'Perdagangan Besar Barang-barang Keperluan Rumah Tangga lainnya'],
            ['code' => '514000', 'name' => 'Perdagangan Besar Produk Antara Bukan Hasil Pertanian, Barang-barang Bekas dan Sisa-sisa Tak Terpakai (Scrap)'],
            ['code' => '514100', 'name' => 'Perdagangan Besar Bahan Bakar Gas, Cair, dan Padat, Serta Produk Sejenis'],
            ['code' => '514200', 'name' => 'Perdagangan Besar Logam dan Bijih Logam'],
            ['code' => '514301', 'name' => 'Perdagangan Dalam Negeri Semen'],
            ['code' => '514302', 'name' => 'Perdagangan Dalam Negeri Besi Beton'],
            ['code' => '514309', 'name' => 'Perdagangan Dalam Negeri Bahan-bahan Konstruksi Lainnya'],
            ['code' => '514901', 'name' => 'Perdagangan Dalam Negeri Pupuk dan Obat Hama'],
            ['code' => '514909', 'name' => 'Perdagangan Dalam Negeri Barang Antara Lainnya'],
            ['code' => '515000', 'name' => 'Perdagangan Besar Mesin-mesin, Suku Cadang dan Perlengkapannya'],
            ['code' => '519000', 'name' => 'Perdagangan Besar Lainnya'],
            ['code' => '519001', 'name' => 'Perdagangan Dalam Negeri Kertas Koran'],
            ['code' => '519009', 'name' => 'Perdagangan Dalam Negeri yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '521000', 'name' => 'Perdagangan Eceran Berbagai Macam Barang'],
            ['code' => '521100', 'name' => 'Perdagangan Eceran Berbagai Macam Barang yang Didominasi Makanan, Minuman dan Tembakau'],
            ['code' => '521900', 'name' => 'Perdagangan Eceran Berbagai Macam Barang yang Didominasi Oleh Barang Bukan Makanan, Minuman dan Tembakau'],
            ['code' => '522000', 'name' => 'Perdagangan Eceran Komoditi Makanan, Minuman, Atau Tembakau'],
            ['code' => '522100', 'name' => 'Perdagangan Eceran Komoditi Makanan dari Hasil Pertanian'],
            ['code' => '522200', 'name' => 'Perdagangan Eceran Komoditi Makanan, Minuman, Atau Tembakau Hasil Industri Pengolahan'],
            ['code' => '523000', 'name' => 'Perdagangan Eceran Komoditi Bukan Makanan, Minuman atau Tembakau'],
            ['code' => '523100', 'name' => 'Perdagangan Eceran Bahan Kimia, Farmasi, Kosmetik, dan Alat Laboratorium'],
            ['code' => '523200', 'name' => 'Perdagangan Eceran Tekstil, Pakaian Jadi, Alas Kaki, dan Barang Keperluan Pribadi'],
            ['code' => '523300', 'name' => 'Perdagangan Eceran Perlengkapan Rumah Tangga dan Perlengkapan Dapur'],
            ['code' => '523400', 'name' => 'Perdagangan Eceran Bahan Konstruksi'],
            ['code' => '523500', 'name' => 'Perdagangan Eceran Bahan Bakar dan Minyak Pelumas'],
            ['code' => '523600', 'name' => 'Perdagangan Eceran Kertas, Barang-barang dari Kertas, Alat Tulis, Barang Cetakan, Alat Olahraga, Alat Musik, Alat Fotografi, Komputer'],
            ['code' => '523700', 'name' => 'Perdagangan Eceran Mesin-mesin (Kecuali Mobil dan Sepeda Motor) dan Suku Cadang (Onderdil), Termasuk Alat-alat Transportasi'],
            ['code' => '523800', 'name' => 'Perdagangan Eceran Barang-barang Kerajinan, Mainan Anak-anak, dan Lukisan'],
            ['code' => '523900', 'name' => 'Perdagangan Eceran Komoditi Lainnya (Bukan Makanan, Minuman, Atau Tembakau)'],
            ['code' => '524000', 'name' => 'Perdagangan Eceran Barang Bekas'],
            ['code' => '525000', 'name' => 'Perdagangan Eceran Kaki Lima'],
            ['code' => '525100', 'name' => 'Perdagangan Eceran Kaki Lima Komoditi dari Hasil Pertanian'],
            ['code' => '525200', 'name' => 'Perdagangan Eceran Kaki Lima Komoditi Makanan, Minuman Hasil Industri Pengolahan'],
            ['code' => '525300', 'name' => 'Perdagangan Eceran Kaki Lima Bahan Kimia, Frmasi, Kosmetik, dan Alat Laboratorium'],
            ['code' => '525400', 'name' => 'Perdagangan Eceran Kaki Lima Tekstil, Pakaian Jadi, Alas Kaki, dan Barang Keperluan Pribadi'],
            ['code' => '525500', 'name' => 'Perdagangan Eceran Kaki Lima Perlengkapan Rumah Tangga dan Perlengkapan Dapur'],
            ['code' => '525600', 'name' => 'Perdagangan Eceran Kaki Lima Bahan Bakar dan Pelumas'],
            ['code' => '525700', 'name' => 'Perdagangan Eceran Kaki Lirna Kertas, Barang-Barang dari Kertas, Alat Tulis, Barang Cetakan, Alat Olah Raga, Alat Musik, Alat Fotografi, dan Komputer'],
            ['code' => '525800', 'name' => 'Perdagangan Eceran Kaki Lima barang-barang kerajinan, mainan anak-anak, dan Iukisan'],
            ['code' => '525900', 'name' => 'Perdagangan Eceran Kaki Lima Barang-Barang Bekas'],
            ['code' => '526000', 'name' => 'Perdagangan Eceran Kaki Lima Lainnya'],
            ['code' => '527000', 'name' => 'Perdagangan Eceran Lainnya'],
            ['code' => '527100', 'name' => 'Perdagangan Eceran Melalui Media'],
            ['code' => '527200', 'name' => 'Perdagangan Eceran Keliling'],
            ['code' => '531000', 'name' => 'Perdagangan Ekspor Berdasarkan Balas Jasa (Fee) Atau Kontrak'],
            ['code' => '532000', 'name' => 'Perdagangan Ekspor Bahan Baku Hasil Pertanian, Binatang Hidup, Makanan, Minuman, dan Tembakau'],
            ['code' => '532111', 'name' => 'Perdagangan Ekspor Biji Kelapa Sawit'],
            ['code' => '532112', 'name' => 'Perdagangan Ekspor Hasil Tanaman Pangan dan Perkebunan'],
            ['code' => '532119', 'name' => 'Perdagangan Ekspor Bahan Baku Hasil Pertanian Lainnya'],
            ['code' => '532120', 'name' => 'Perdagangan Ekspor Binatang Hidup'],
            ['code' => '532130', 'name' => 'Perdagangan Ekspor Hasil Perikanan'],
            ['code' => '532141', 'name' => 'Perdagangan Ekspor Kayu'],
            ['code' => '532142', 'name' => 'Perdagangan Ekspor Rotan'],
            ['code' => '532149', 'name' => 'Perdagangan Ekspor Hasil Hutan Selain Kayu dan Rotan'],
            ['code' => '532201', 'name' => 'Perdagangan Ekspor Udang Olahan'],
            ['code' => '532202', 'name' => 'Perdagangan Ekspor Teh'],
            ['code' => '532203', 'name' => 'Perdagangan Ekspor Kopi Bubuk'],
            ['code' => '532204', 'name' => 'Perdagangan Ekspor Tembakau'],
            ['code' => '532209', 'name' => 'Perdagangan Ekspor Makanan dan Minuman Lainnya'],
            ['code' => '533000', 'name' => 'Perdagangan Ekspor Barang-barang Keperluan Rumah Tangga'],
            ['code' => '533101', 'name' => 'Perdagangan Ekspor Tekstil'],
            ['code' => '533102', 'name' => 'Perdagangan Ekspor Pakaian Jadi'],
            ['code' => '533103', 'name' => 'Perdagangan Ekspor Kulit'],
            ['code' => '533900', 'name' => 'Perdagangan Ekspor Barang-barang Keperluan Rumah Tangga Lainnya'],
            ['code' => '534000', 'name' => 'Perdagangan Ekspor Produk Antara (Intermediate Products) Bukan Hasil Pertanian, Barang-barang Bekas dan Sisa-sisa Tak Terpakai (Scrap)'],
            ['code' => '534100', 'name' => 'Perdagangan Ekspor Bahan Bakar Gas, Cair, dan Padat Serta Produk Sejenis'],
            ['code' => '534201', 'name' => 'Perdagangan Ekspor Bijih Timah'],
            ['code' => '534202', 'name' => 'Perdagangan Ekspor Bijih Logam Selain Timah'],
            ['code' => '534203', 'name' => 'Perdagangan Ekspor Batu Bara'],
            ['code' => '534209', 'name' => 'Perdagangan Ekspor Logam dan Bijih Logam (hasil Pertambangan dan Penggalian) Lainnya'],
            ['code' => '534301', 'name' => 'Perdagangan Ekspor Kayu Lapis'],
            ['code' => '534309', 'name' => 'Perdagangan Ekspor Bahan-bahan Konstruksi (kecuali Bahan Hasil Penggalian) Lainnya'],
            ['code' => '534900', 'name' => 'Perdagangan Ekspor Produk Antara (Intermediate Products), Barang-barang Bekas dan Sisa-sisa Tak Terpakai (Scrap)'],
            ['code' => '535000', 'name' => 'Perdagangan Ekspor Mesin-mesin, Suku Cadang dan Perlengkapannya'],
            ['code' => '539000', 'name' => 'Perdagangan Ekspor Lainnya'],
            ['code' => '539011', 'name' => 'Perdagangan Ekspor Kayu Gergajian'],
            ['code' => '539012', 'name' => 'Perdagangan Ekspor Kopi Bijian'],
            ['code' => '539013', 'name' => 'Perdagangan Ekspor Tembakau'],
            ['code' => '539014', 'name' => 'Perdagangan Ekspor Karet'],
            ['code' => '539015', 'name' => 'Perdagangan Ekspor Lada'],
            ['code' => '539016', 'name' => 'Perdagangan Ekspor Minyak Kelapa Sawit Mentah'],
            ['code' => '539017', 'name' => 'Perdagangan Ekspor Minyak Biji Kelapa Sawit'],
            ['code' => '539018', 'name' => 'Perdagangan Ekspor Bungkil Kopra'],
            ['code' => '539019', 'name' => 'Perdagangan Ekspor Hasil Pertanian, Perkebunan, dan Kehutanan Lainnya'],
            ['code' => '539021', 'name' => 'Perdagangan Ekspor Hewan yang Sudah Diolah'],
            ['code' => '539022', 'name' => 'Perdagangan Ekspor Bahan Makanan Lainnya'],
            ['code' => '539023', 'name' => 'Perdagangan Ekspor Hasil Tambang Setengah Jadi'],
            ['code' => '539029', 'name' => 'Perdagangan Ekspor Barang Setengah Jadi Lainnya'],
            ['code' => '539031', 'name' => 'Perdagangan Ekspor Barang Kerajinan dari Kayu dan Rotan'],
            ['code' => '539032', 'name' => 'Perdagangan Ekspor Barang Kerajinan selain dari Kayu dan Rotan'],
            ['code' => '539034', 'name' => 'Perdagangan Ekspor Jasa Konstruksi'],
            ['code' => '539039', 'name' => 'Perdagangan Ekspor yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '541000', 'name' => 'Perdagangan Impor Berdasarkan Balas Jasa (Fee) Atau Kontrak'],
            ['code' => '542000', 'name' => 'Perdagangan Impor Bahan Baku Hasil Pertanian, Binatang Hidup, Makanan, Minuman, dan Tembakau'],
            ['code' => '542101', 'name' => 'Perdagangan Impor Cengkeh'],
            ['code' => '542102', 'name' => ' Perdagangan Impor Biji Gandum'],
            ['code' => '542103', 'name' => 'Perdagangan Impor Jagung'],
            ['code' => '542104', 'name' => 'Perdagangan Impor Kacang Kedelai'],
            ['code' => '542109', 'name' => 'Perdagangan Impor Bahan Baku Hasil Pertanian, dan Binatang Hidup Lainnya'],
            ['code' => '542201', 'name' => 'Perdagangan Impor Beras'],
            ['code' => '542202', 'name' => 'Perdagangan Impor Gula'],
            ['code' => '542209', 'name' => 'Perdagangan Impor Makanan, Minuman, dan Tembakau Lainnya'],
            ['code' => '543000', 'name' => 'Perdagangan Impor Barang-barang Keperluan Rumah Tangga'],
            ['code' => '543100', 'name' => 'Perdagangan Impor Tekstil, Pakaian Jadi, dan Kulit'],
            ['code' => '543900', 'name' => 'Perdagangan Impor Barang-barang Keperluan Rumah Tangga lainnya'],
            ['code' => '544000', 'name' => 'Perdagangan Impor Produk Antara Bukan Hasil Pertanian, Barang-barang Bekas dan Sisa-sisa Tak Terpakai (Scrap)'],
            ['code' => '544100', 'name' => 'Perdagangan Impor Bahan Bakar Gas, Cair, dan Padat Serta Produk Sejenis'],
            ['code' => '544200', 'name' => 'Perdagangan Impor Logam dan Bijih Logam'],
            ['code' => '544301', 'name' => 'Perdagangan Impor Besi Beton'],
            ['code' => '544309', 'name' => 'Perdagangan Impor Bahan-bahan Konstruksi Lainnya'],
            ['code' => '544901', 'name' => 'Perdagangan Impor Pupuk dan Obat Hama'],
            ['code' => '544902', 'name' => 'Perdagangan Impor Farmasi'],
            ['code' => '544909', 'name' => 'Perdagangan Impor Barang Antara Lainnya'],
            ['code' => '545000', 'name' => 'Perdagangan Impor Mesin-mesin, Suku Cadang dan Perlengkapannya'],
            ['code' => '545001', 'name' => 'Perdagangan Impor Suku Cadang Industri'],
            ['code' => '545009', 'name' => 'Perdagangan Impor Suku Cadang Mesin-mesin, Suku Cadang dan Perlengkapannya Lainnya'],
            ['code' => '549000', 'name' => 'Perdagangan Impor Lainnya'],
            ['code' => '551100', 'name' => 'Hotel Bintang'],
            ['code' => '551200', 'name' => 'Hotel Melati'],
            ['code' => '551900', 'name' => 'Jasa Akomodasi Lainnya'],
            ['code' => '552100', 'name' => 'Restoran / Rumah Makan'],
            ['code' => '552009', 'name' => 'Penyediaan Makan Minum Lainnya'],
            ['code' => '601000', 'name' => 'Angkutan Jalan Rel'],
            ['code' => '602100', 'name' => 'Angkutan Jalan Dalam Trayek Untuk Penumpang'],
            ['code' => '602200', 'name' => 'Angkutan Jalan Tidak Dalam Trayek Untuk Penumpang'],
            ['code' => '602300', 'name' => 'Angkutan Jalan Untuk Barang'],
            ['code' => '603000', 'name' => 'Angkutan Dengan Saluran Pipa'],
            ['code' => '611100', 'name' => 'Angkutan Laut Domestik'],
            ['code' => '611200', 'name' => 'Angkutan Laut Internasional'],
            ['code' => '612000', 'name' => 'Angkutan Sungai, danau, dan penyeberangan'],
            ['code' => '612100', 'name' => 'Angkutan Sungai dan Danau'],
            ['code' => '612200', 'name' => 'Angkutan Penyeberangan Domestik'],
            ['code' => '621000', 'name' => 'Angkutan Udara Berjadwal'],
            ['code' => '622000', 'name' => 'Angkutan Udara Tidak Berjadwal'],
            ['code' => '623000', 'name' => 'Angkutan Udara Khusus'],
            ['code' => '631000', 'name' => 'Jasa Pelayanan Bongkar Muat Barang'],
            ['code' => '632000', 'name' => 'Pergudangan, Jasa Cold Storage, dan Jasa Wilayah Berikat'],
            ['code' => '633000', 'name' => 'Jasa Penunjang Angkutan Kecuali Jasa Bongkar Muat dan Pergudangan'],
            ['code' => '634000', 'name' => 'Jasa Perjalanan Wisata'],
            ['code' => '635000', 'name' => 'Jasa Pengiriman dan Pengepakan'],
            ['code' => '641000', 'name' => 'Pos Nasional, Unit Pelayanan Pos dan Jasa Kurir'],
            ['code' => '642000', 'name' => 'Jaringan Telekomunikasi'],
            ['code' => '643000', 'name' => 'Jasa Telekomunikasi'],
            ['code' => '644000', 'name' => 'Telekomunikasi Khusus'],
            ['code' => '651000', 'name' => 'Perantara Moneter (Bank)'],
            ['code' => '659000', 'name' => 'Perantara Keuangan Lainnya (Non Bank)'],
            ['code' => '659001', 'name' => 'Perantara Keuangan Lainnya (Non Bank) Leasing'],
            ['code' => '659009', 'name' => 'Perantara Keuangan Lainnya (Non Bank) Selain Leasing'],
            ['code' => '660000', 'name' => 'Asuransi dan Dana Pensiun'],
            ['code' => '671000', 'name' => 'Jasa Penunjang Perantara Keuangan Kecuali Asuransi dan Dana Pensiun'],
            ['code' => '672000', 'name' => 'Jasa Penunjang Asuransi dan dana Pensiun'],
            ['code' => '701001', 'name' => 'Real Estate Perumahan Sederhana - Perumnas'],
            ['code' => '701002', 'name' => 'Real Estate Perumahan Sederhana - Selain Perumnas s.d. Tipe 21'],
            ['code' => '701003', 'name' => 'Real Estate Perumahan Sederhana - Selain Perumnas s.d. Tipe 22 s.d. 70'],
            ['code' => '701004', 'name' => 'Real Estate Perumahan Menengah, Besar Atau Mewah (Tipe Diatas 70)'],
            ['code' => '701005', 'name' => 'Real Estate Perumahan Flat / Apartemen'],
            ['code' => '701006', 'name' => 'Real Estate Gedung Perbelanjaan (Mal, Plaza)'],
            ['code' => '701007', 'name' => 'Real Estate Gedung Perkantoran'],
            ['code' => '701008', 'name' => 'Real Estate Gedung Rumah Toko (Ruko) atau Rumah Kantor (Rukan)'],
            ['code' => '701009', 'name' => 'Real Estate Lainnya'],
            ['code' => '702000', 'name' => 'Real Estate Atas Dasar Balas Jasa (Fee) Atau Kontrak'],
            ['code' => '703000', 'name' => 'Kawasan Pariwisata dan Penyediaan Sarana Wisata Tirta Kawasan Pariwisata'],
            ['code' => '711100', 'name' => 'Persewaan Alat Transportasi Darat'],
            ['code' => '711200', 'name' => 'Persewaan Alat Transportasi Air'],
            ['code' => '711300', 'name' => 'Persewaan Alat Transportasi Udara'],
            ['code' => '712100', 'name' => 'Persewaan Mesin Pertanian dan Peralatannya'],
            ['code' => '712200', 'name' => 'Persewaan Mesin Konstruksi dan Teknik Sipil dan Peralatannya'],
            ['code' => '712300', 'name' => 'Persewaan Mesin Kantor dan Peralatannya (Termasuk Komputer)'],
            ['code' => '712900', 'name' => 'Persewaan Mesin Lainnya dan Peralatannya yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '713000', 'name' => 'Persewaan Barang-barang Keperluan Rumah Tangga dan Pribadi yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '721000', 'name' => 'Jasa Konsultasi Piranti Keras (Hardware Consulting)'],
            ['code' => '722000', 'name' => 'Jasa Konsultasi Piranti Lunak (Software Consulting)'],
            ['code' => '723000', 'name' => 'Pengolahan Data'],
            ['code' => '724000', 'name' => 'Jasa Kegiatan Data Base'],
            ['code' => '725000', 'name' => 'Perawatan dan Reparasi Mesin-mesin Kantor, Akuntansi, dan Komputer'],
            ['code' => '729000', 'name' => 'Kegiatan Lain yang Berkaitan Dengan Komputer'],
            ['code' => '731000', 'name' => 'Penelitian dan Pengembangan Ilmu Pengetahuan Alam dan Teknologi'],
            ['code' => '732000', 'name' => 'Penelitian dan Pengembangan Ilmu Pengetahuan Sosial dan Humaniora'],
            ['code' => '741000', 'name' => 'Jasa Hukum, Akuntansi dan Pembukuan, Konsultasi Pajak, Penelitian Pasar, dan Konsultasi Bisnis dan Manajemen'],
            ['code' => '742000', 'name' => 'Jasa Konsultasi Arsitek, Kegiatan Teknik dan Rekayasa, Serta Analisis dan Testing'],
            ['code' => '743000', 'name' => 'Jasa Periklanan'],
            ['code' => '749000', 'name' => 'Jasa Perusahaan Lainnya yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '749001', 'name' => 'Pedagang Valuta Asing'],
            ['code' => '749009', 'name' => 'Jasa Perusahaan Lainnya'],
            ['code' => '751000', 'name' => 'Administrasi Pemerintahan, dan Kebijaksanaan Ekonomi dan Sosial'],
            ['code' => '752000', 'name' => 'Hubungan Luar Negeri, Pertahanan, dan Keamanan'],
            ['code' => '753000', 'name' => 'Jaminan Sosial Wajib'],
            ['code' => '801000', 'name' => 'Jasa Pendidikan Dasar'],
            ['code' => '802000', 'name' => 'Jasa Pendidikan Menengah'],
            ['code' => '803000', 'name' => 'Jasa Pendidikan Tinggi'],
            ['code' => '804000', 'name' => 'Jasa Pendidikan Lainnya'],
            ['code' => '851001', 'name' => 'Jasa Kesehatan Manusia - Rumah sakit'],
            ['code' => '851002', 'name' => 'Jasa Kesehatan Manusia - Poliklinik / Rumah Bersalin'],
            ['code' => '851003', 'name' => 'Jasa Kesehatan Manusia - Tempat Perawatan / Pengobatan'],
            ['code' => '851004', 'name' => 'Jasa Kesehatan Manusia - Profesi Dokter'],
            ['code' => '852000', 'name' => 'Jasa Kesehatan Hewan'],
            ['code' => '853000', 'name' => 'Jasa Kegiatan Sosial'],
            ['code' => '900000', 'name' => 'Jasa Kebersihan'],
            ['code' => '910000', 'name' => 'Organisasi Bisnis, Pengusaha dan Profesional'],
            ['code' => '912000', 'name' => 'Organisasi Buruh'],
            ['code' => '919000', 'name' => 'Organisasi Lainnya'],
            ['code' => '921000', 'name' => 'Kegiatan Perfilman, Radio, Televisi, dan Hiburan Lainnya'],
            ['code' => '922000', 'name' => 'Kegiatan Kantor Berita'],
            ['code' => '923000', 'name' => 'Perpustakaan, Arsip, Museum, dan Kegiatan Kebudayaan Lainnya'],
            ['code' => '930000', 'name' => 'Jasa Kegiatan Lainnya'],
            ['code' => '950000', 'name' => 'Jasa Perorangan yang Melayani Rumah Tangga'],
            ['code' => '990000', 'name' => 'Badan Internasional dan Badan Ekstra Internasional Lainnya'],
            ['code' => '000001', 'name' => 'Kegiatan yang Belum Jelas Batasannya Perorangan'],
            ['code' => '000002', 'name' => 'Kegiatan yang Belum Jelas Batasannya Badan Usaha'],
            ['code' => '001000', 'name' => 'Rumah Tangga untuk Pemilikan Perumahan'],
            ['code' => '001100', 'name' => 'Rumah Tangga untuk Pemilikan Rumah Tinggal'],
            ['code' => '001110', 'name' => 'Rumah Tangga untuk Pemilikan Rumah Tinggal s.d. Tipe 21'],
            ['code' => '001120', 'name' => 'Rumah Tangga untuk Pemilikan Rumah Tinggal Tipe 22 s.d. 70'],
            ['code' => '001130', 'name' => 'Rumah Tangga untuk Pemilikan Rumah Tinggal Tipe Diatas 70'],
            ['code' => '001200', 'name' => 'Rumah Tangga untuk Pemilikan Flat atau Apartemen'],
            ['code' => '001210', 'name' => 'Rumah Tangga untuk Pemilikan Flat atau Apartemen s.d. Tipe 21'],
            ['code' => '001220', 'name' => 'Rumah Tangga untuk Pemilikan Flat atau Apartemen Tipe 22 s.d. 70'],
            ['code' => '001230', 'name' => 'Rumah Tangga untuk Pemilikan Flat atau Apartemen Tipe Diatas 70'],
            ['code' => '001300', 'name' => 'Rumah Tangga untuk Pemilikan Rumah Toko (Ruko) atau Rumah Kantor (Rukan)'],
            ['code' => '002000', 'name' => 'Rumah Tangga untuk Pemilikan Kendaraan Bermotor'],
            ['code' => '002100', 'name' => 'Rumah Tangga untuk Pemilikan Mobil Roda Empat'],
            ['code' => '002200', 'name' => 'Rumah Tangga untuk Pemilikan Sepeda Bermotor'],
            ['code' => '002300', 'name' => 'Rumah Tangga untuk Pemilikan Truk dan Kendaraan Bermotor Roda Enam atau Lebih'],
            ['code' => '002900', 'name' => 'Rumah Tangga untuk Pemilikan Kendaraan Bermotor Lainnya'],
            ['code' => '003000', 'name' => 'Rumah Tangga untuk Pemilikan Peralatan Rumah Tangga Lainnya'],
            ['code' => '003100', 'name' => 'Rumah Tangga untuk Pemilikan Furnitur dan Peralatan Rumah Tangga'],
            ['code' => '003200', 'name' => 'Rumah Tangga untuk Pemilikan Televisi, Radio, dan Alat Elektronik'],
            ['code' => '003300', 'name' => 'Rumah Tangga untuk Pemilikan Komputer dan Alat Komunikasi'],
            ['code' => '003900', 'name' => 'Rumah Tangga untuk Pemilikan Peralatan Lainnya'],
            ['code' => '004000', 'name' => 'Rumah Tangga untuk Keperluan yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '004100', 'name' => 'Rumah Tangga untuk Keperluan Multiguna'],
            ['code' => '004900', 'name' => 'Rumah Tangga untuk Keperluan yang Tidak Diklasifikasikan di Tempat Lain'],
            ['code' => '009000', 'name' => 'Bukan Lapangan Usaha Lainnya'],
        ];

        foreach ($sectors as $sector) {
            EconomicSector::firstOrCreate(
                ['code' => $sector['code']],
                ['name' => $sector['name']]
            );
        }
    }
}
