<?php

namespace Database\Seeders;

use App\Models\NonBankThirdParty;
use Illuminate\Database\Seeder;

class NonBankThirdPartySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $parties = [
            ['code' => '0010', 'name' => 'Kantor Perbendaharaan dan Kas Negara (KPKN)'],
            ['code' => '0020', 'name' => 'Departemen Keuangan'],
            ['code' => '0030', 'name' => 'Departemen Pertahanan'],
            ['code' => '0040', 'name' => 'Departemen Kehutanan'],
            ['code' => '0050', 'name' => 'Departemen Pertanian'],
            ['code' => '0060', 'name' => 'Departemen Pertambangan dan Energi'],
            ['code' => '0070', 'name' => 'Departemen Agama'],
            ['code' => '0080', 'name' => 'Kementrian Negara BUMN'],
            ['code' => '0999', 'name' => 'Departemen lainnya'],
            ['code' => '1010', 'name' => 'Pemerintah Provinsi'],
            ['code' => '1020', 'name' => 'Pemerintah Kota'],
            ['code' => '1030', 'name' => 'Pemerintah Kabupaten'],
            ['code' => '2010', 'name' => 'Badan Urusan Logistik (BULOG)'],
            ['code' => '2020', 'name' => 'Lembaga Penjamin Simpanan (LPS)'],
            ['code' => '2090', 'name' => 'Badan dan Lembaga Pemerintah Lainnya'],
            ['code' => '4111', 'name' => 'Jamsostek'],
            ['code' => '4112', 'name' => 'Taspen'],
            ['code' => '4113', 'name' => 'Jiwasraya'],
            ['code' => '4114', 'name' => 'Jasa Raharja'],
            ['code' => '4115', 'name' => 'Jasindo'],
            ['code' => '4116', 'name' => 'ASABRI'],
            ['code' => '4119', 'name' => 'Perusahaan asuransi lainnya (BUMN atau Pemerintah Campuran)'],
            ['code' => '4120', 'name' => 'Dana Pensiun (BUMN atau Pemerintah Campuran)'],
            ['code' => '4130', 'name' => 'Modal Ventura (BUMN atau Pemerintah Campuran)'],
            ['code' => '4140', 'name' => 'Perusahaan Pembiayaan (BUMN atau Pemerintah Campuran)'],
            ['code' => '4151', 'name' => 'Perusahaan sekuritas yang tidak melakukan kegiatan usaha Reksadana (BUMN atau Pemerintah Campuran)'],
            ['code' => '4152', 'name' => 'Perusahaan sekuritas yang melakukan kegiatan usaha Reksadana (BUMN atau Pemerintah Campuran)'],
            ['code' => '4153', 'name' => 'Perusahaan Reksadana (BUMN atau Pemerintah Campuran)'],
            ['code' => '4154', 'name' => 'Manajer Investasi (BUMN atau Pemerintah Campuran)'],
            ['code' => '4155', 'name' => 'PT Danareksa'],
            ['code' => '4159', 'name' => 'Perusahaan Sekuritas dan Reksadana Lainnya (BUMN atau Pemerintah Campuran)'],
            ['code' => '4171', 'name' => 'Perum Pegadaian'],
            ['code' => '4172', 'name' => 'PT Pos Indonesia'],
            ['code' => '4173', 'name' => 'Lembaga Pembiayaan Ekspor Indonesia'],
            ['code' => '4179', 'name' => 'Lembaga Keuangan Non Bank Lainnya (BUMN atau Pemerintah Campuran)'],
            ['code' => '4501', 'name' => 'PT Kereta Api Indonesia (KAI)'],
            ['code' => '4502', 'name' => 'PT Pelayaran Nasional Indonesia (PELNI)'],
            ['code' => '4503', 'name' => 'PT Pelabuhan Laut Indonesia (PELINDO)'],
            ['code' => '4504', 'name' => 'PT Angkutan Sungai, Danau dan Penyeberangan (ASDP)'],
            ['code' => '4505', 'name' => 'PT Angkasa Pura'],
            ['code' => '4506', 'name' => 'PT Perkebunan Nusantara'],
            ['code' => '4507', 'name' => 'PT Pertamina'],
            ['code' => '4508', 'name' => 'PT Perusahaan Listrik Negara (PLN)'],
            ['code' => '4509', 'name' => 'PT Krakatau Steel'],
            ['code' => '4510', 'name' => 'PT Garuda Indonesia'],
            ['code' => '4511', 'name' => 'PT Telkom'],
            ['code' => '4512', 'name' => 'PT Indosat'],
            ['code' => '4513', 'name' => 'PT Jasa Marga'],
            ['code' => '4514', 'name' => 'PT Timah'],
            ['code' => '4515', 'name' => 'PT Aneka Tambang'],
            ['code' => '4516', 'name' => 'Perusahaan Jasa Konstruksi (BUMN atau Pemerintah Campuran)'],
            ['code' => '4599', 'name' => 'Lainnya (BUMN atau Pemerintah Campuran)'],
            ['code' => '5110', 'name' => 'Perusahaan Asuransi (BUMD)'],
            ['code' => '5120', 'name' => 'Dana Pensiun  (BUMD)'],
            ['code' => '5130', 'name' => 'Modal Ventura  (BUMD)'],
            ['code' => '5140', 'name' => 'Perusahaan Pembiayaan  (BUMD)'],
            ['code' => '5151', 'name' => 'Perusahaan sekuritas yang tidak melakukan kegiatan usaha reksadana  (BUMD)'],
            ['code' => '5152', 'name' => 'Perusahaan sekuritas yang melakukan kegiatan usaha reksadana  (BUMD)'],
            ['code' => '5153', 'name' => 'Perusahaan Reksadana  (BUMD)'],
            ['code' => '5154', 'name' => 'Manajer Investasi  (BUMD)'],
            ['code' => '5159', 'name' => 'Perusahaan Sekuritas Lainnya  (BUMD)'],
            ['code' => '5199', 'name' => 'Lembaga Keuangan Non Bank Lainnya  (BUMD)'],
            ['code' => '5501', 'name' => 'Perusahaan Daerah Air Minum (PDAM)'],
            ['code' => '5502', 'name' => 'Perusahaan Daerah Pasar (PD Pasar)'],
            ['code' => '5599', 'name' => 'Lainnya (BUMD)'],
            ['code' => '7110', 'name' => 'Perusahaan Asuransi (Swasta Nasional)'],
            ['code' => '7120', 'name' => 'Dana Pensiun (Swasta Nasional)'],
            ['code' => '7130', 'name' => 'Modal Ventura (Swasta Nasional)'],
            ['code' => '7140', 'name' => 'Perusahaan Pembiayaan (Swasta Nasional)'],
            ['code' => '7151', 'name' => 'Perusahaan sekuritas yang tidak melakukan kegiatan usaha Reksadana (Swasta Nasional)'],
            ['code' => '7152', 'name' => 'Perusahaan sekuritas yang melakukan kegiatan usaha Reksadana (Swasta Nasional)'],
            ['code' => '7153', 'name' => 'Perusahaan Reksadana (Swasta Nasional)'],
            ['code' => '7154', 'name' => 'Manajer Investasi (Swasta Nasional)'],
            ['code' => '7159', 'name' => 'Perusahaan Skuritas Lainnya (Swasta Nasional)'],
            ['code' => '7172', 'name' => 'Baitul Maal Wa Tamwil/BMT (Swasta Nasional)'],
            ['code' => '7173', 'name' => 'Koperasi Primer (Swasta Nasional)'],
            ['code' => '7174', 'name' => 'Koperasi Lainnya (Swasta Nasional)'],
            ['code' => '7190', 'name' => 'Lembaga Keuangan Non Bank Lainnya (Swasta Nasional)'],
            ['code' => '7210', 'name' => 'Perusahaan Asuransi (Swasta Campuran)'],
            ['code' => '7220', 'name' => 'Dana pensiun (Swasta Campuran)'],
            ['code' => '7230', 'name' => 'Modal Ventura (Swasta Campuran)'],
            ['code' => '7240', 'name' => 'Perusahaan Pembiayaan (Swasta Campuran)'],
            ['code' => '7251', 'name' => 'Perusahaan sekuritas yang tidak melakukan kegiatan usaha Reksadana (Swasta Campuran)'],
            ['code' => '7252', 'name' => 'Perusahaan sekuritas yang melakukan kegiatan usaha Reksadana (Swasta Campuran)'],
            ['code' => '7253', 'name' => 'Perusahaan Reksadana (Swasta Campuran)'],
            ['code' => '7254', 'name' => 'Manajer Investasi (Swasta Campuran)'],
            ['code' => '7259', 'name' => 'Perusahaan Sekuritas dan Reksadana Lainnya (Swasta Campuran)'],
            ['code' => '7272', 'name' => 'Baitul Maal Wa Tamwil/BMT (Swasta Campuran)'],
            ['code' => '7273', 'name' => 'Kantor Perwakilan Lembaga Milik Asing di Indonesia lainnya (Swasta Campuran)'],
            ['code' => '7290', 'name' => 'Lembaga Keuangan Non Bank Lainnya (Swasta Campuran)'],
            ['code' => '7310', 'name' => 'Perusahaan Asuransi (Asing)'],
            ['code' => '7320', 'name' => 'Dana Pensiun (Asing)'],
            ['code' => '7330', 'name' => 'Modal Ventura (Asing)'],
            ['code' => '7340', 'name' => 'Perusahaan Pembiayaan (Asing)'],
            ['code' => '7351', 'name' => 'Perusahaan sekuritas yang tidak melakukan kegiatan usaha Reksadana (Asing)'],
            ['code' => '7352', 'name' => 'Perusahaan sekuritas yang melakukan kegiatan usaha Reksadana (Asing)'],
            ['code' => '7353', 'name' => 'Perusahaan Reksadana (Asing)'],
            ['code' => '7354', 'name' => 'Manajer Investasi (Asing)'],
            ['code' => '7359', 'name' => 'Perusahaan Sekuritas dan Reksadana Lainnya (Asing)'],
            ['code' => '7372', 'name' => 'Baitul Maal Wa Tamwil/BMT (Asing)'],
            ['code' => '7379', 'name' => 'Kantor Perwakilan Lembaga Milik Asing di Indonesia lainnya (Asing)'],
            ['code' => '7390', 'name' => 'Lembaga Keuangan Non Bank Lainnya (Asing)'],
            ['code' => '8111', 'name' => 'Perusahaan Otomotif (Swasta Nasional)'],
            ['code' => '8112', 'name' => 'Perusahaan Perminyakan (Swasta Nasional)'],
            ['code' => '8113', 'name' => 'Perusahaan Tekstil (Swasta Nasional)'],
            ['code' => '8114', 'name' => 'Perusahaan Perkayuan/HPH (Swasta Nasional)'],
            ['code' => '8115', 'name' => 'Perusahaan Jasa Konstruksi (Swasta Nasional)'],
            ['code' => '8116', 'name' => 'Perusahaan Industri Rokok (Swasta Nasional)'],
            ['code' => '8117', 'name' => 'Perusahaan Industri Makanan (Swasta Nasional)'],
            ['code' => '8118', 'name' => 'Perusahaan Agrobusiness (Swasta Nasional)'],
            ['code' => '8139', 'name' => 'Perusahaan Lainnya (Swasta Nasional)'],
            ['code' => '8141', 'name' => 'Koperasi Bukan Simpan Pinjam Primer (Swasta Nasional)'],
            ['code' => '8149', 'name' => 'Koperasi Bukan Simpan Pinjam Lainnya (Swasta Nasional)'],
            ['code' => '8151', 'name' => 'Badan Amil Zakat Infaq dan Shadaqah/BAZIS (Swasta Nasional)'],
            ['code' => '8152', 'name' => 'Lembaga Pendidikan (Swasta Nasional)'],
            ['code' => '8159', 'name' => 'Yayasan, Badan Sosial, dan Organisasi Kemasyarakatan Lainnya (Swasta Nasional)'],
            ['code' => '8411', 'name' => 'Perusahaan Otomotif (Swasta Campuran)'],
            ['code' => '8412', 'name' => 'Perusahaan Perminyakan (Swasta Campuran)'],
            ['code' => '8413', 'name' => 'Perusahaan Tekstil (Swasta Campuran)'],
            ['code' => '8414', 'name' => 'Perusahaan Perkayuan/HPH (Swasta Campuran)'],
            ['code' => '8415', 'name' => 'Perusahaan Jasa Konstruksi (Swasta Campuran)'],
            ['code' => '8416', 'name' => 'Perusahaan Industri Rokok (Swasta Campuran)'],
            ['code' => '8417', 'name' => 'Perusahaan Industri Makanan (Swasta Campuran)'],
            ['code' => '8418', 'name' => 'Perusahaan Agrobusiness (Swasta Campuran)'],
            ['code' => '8449', 'name' => 'Perusahaan Lainnya (Swasta Campuran)'],
            ['code' => '8451', 'name' => 'Badan Amil Zakat Infaq dan Shadaqah/BAZIS (Swasta Campuran)'],
            ['code' => '8452', 'name' => 'Lembaga Pendidikan (Swasta Campuran)'],
            ['code' => '8469', 'name' => 'Yayasan, Badan Sosial, dan Organisasi Kemasyarakatan Lainnya (Swasta Campuran)'],
            ['code' => '8480', 'name' => 'Kantor Perwakilan Lembaga Milik Asing di Indonesia (Swasta Campuran)'],
            ['code' => '8611', 'name' => 'Perusahaan Otomotif (Asing)'],
            ['code' => '8612', 'name' => 'Perusahaan Perminyakan (Asing)'],
            ['code' => '8613', 'name' => 'Perusahaan Tekstil (Asing)'],
            ['code' => '8614', 'name' => 'Perusahaan Perkayuan/HPH (Asing)'],
            ['code' => '8615', 'name' => 'Perusahaan Jasa Konstruksi (Asing)'],
            ['code' => '8616', 'name' => 'Perusahaan Industri Rokok (Asing)'],
            ['code' => '8617', 'name' => 'Perusahaan Industri Makanan (Asing)'],
            ['code' => '8618', 'name' => 'Perusahaan Agrobisnis (Asing)'],
            ['code' => '8619', 'name' => 'Perusahaan Lainnya (Asing)'],
            ['code' => '8651', 'name' => 'Badan Amil Zakat Infaq dan Shadaqah/BAZIS (Asing)'],
            ['code' => '8652', 'name' => 'Lembaga Pendidikan (Asing)'],
            ['code' => '8659', 'name' => 'Yayasan, Badan Sosial, dan Organisasi Kemasyarakatan Lainnya (Asing)'],
            ['code' => '8670', 'name' => 'Kantor Perwakilan Lembaga Milik Asing di Indonesia (Asing)'],
            ['code' => '8900', 'name' => 'Sektor Swasta Lainnya (Perusahaan/Bank dilikuidasi)'],
            ['code' => '9000', 'name' => 'Perseorangan (Penduduk)'],
            ['code' => '9100', 'name' => 'Pemerintah Pusat Asing'],
            ['code' => '9200', 'name' => 'Perwakilan negara-negara asing dan stafnya'],
            ['code' => '9300', 'name' => 'BUMN milik negara asing'],
            ['code' => '9400', 'name' => 'Lembaga-lembaga keuangan bukan bank yang beroperasi di luar Indonesia'],
            ['code' => '9501', 'name' => 'Swasta Patungan Indonesia dan Negara Asing di luar negeri'],
            ['code' => '9502', 'name' => 'Swasta Milik Indonesia di luar negeri'],
            ['code' => '9519', 'name' => 'Lainnya di luar negeri'],
            ['code' => '9611', 'name' => 'Islamic Development Bank (IDB)'],
            ['code' => '9612', 'name' => 'Asian Development Bank (ADB)'],
            ['code' => '9613', 'name' => 'World Bank'],
            ['code' => '9629', 'name' => 'Bank Pembanguna Multilateral lainnya'],
            ['code' => '9690', 'name' => 'Lembaga Internasional Lainnya'],
            ['code' => '9700', 'name' => 'Perseorangan (Bukan Penduduk)'],
        ];
        foreach ($parties as $party) {
            NonBankThirdParty::firstOrCreate(
                ['code' => $party['code']],
                ['name' => $party['name']]
            );
        }
    }
}
